package com.eleckoi.android.feature.preferences

import androidx.datastore.preferences.core.booleanPreferencesKey
import androidx.datastore.preferences.core.floatPreferencesKey
import androidx.datastore.preferences.core.intPreferencesKey
import androidx.datastore.preferences.core.stringPreferencesKey

internal val PinnedChatIdsJson = stringPreferencesKey("pinned_chat_ids_json")
internal val HiddenChatIdsJson = stringPreferencesKey("hidden_chat_ids_json")
internal val SearchHistoryJson = stringPreferencesKey("search_history_json")
internal val LastActiveChatSessionId = stringPreferencesKey("last_active_chat_session_id")
internal val ActiveChatSessionIdsJson = stringPreferencesKey("active_chat_session_ids_json")
internal val PinnedCreatorWorkspaceIdsJson = stringPreferencesKey("pinned_creator_workspace_ids_json")
internal val CreatorWorkspaceExpansionOverridesJson =
    stringPreferencesKey("creator_workspace_expansion_overrides_json")
internal val LastCreatorWorkspaceId = stringPreferencesKey("last_creator_workspace_id")
internal val HistorySaveMode = stringPreferencesKey("history_save_mode")
internal val AppearanceModeKey = stringPreferencesKey("appearance_mode")
internal val NewCharacterBackgroundKey = stringPreferencesKey("new_character_background")
// Keep the PC storage name and values so portable preference snapshots agree across clients.
internal val SidebarCharacterArtwork = stringPreferencesKey("sidebar_character_artwork")
internal val DefaultChatConfigId = stringPreferencesKey("default_chat_config_id")
internal val DefaultChatModel = stringPreferencesKey("default_chat_model")
internal val AssistantBubbleEnabledSocial = booleanPreferencesKey("assistant_bubble_enabled_social")
internal val AssistantBubbleEnabledAgent = booleanPreferencesKey("assistant_bubble_enabled_agent")
internal val AssistantBubbleEnabledRoleplay = booleanPreferencesKey("assistant_bubble_enabled_roleplay")
internal val ChatLayoutModeKey = stringPreferencesKey("chat_layout_mode")
internal val ChatReasoningDisplayModeKey = stringPreferencesKey("chat_reasoning_display_mode")
internal val ChatToolTimelineStyleKey = stringPreferencesKey("chat_tool_timeline_style")
internal val ChatGenerationStatsEnabled = booleanPreferencesKey("chat_generation_stats_enabled")
internal val ChatCodeBlockStyleKey = stringPreferencesKey("chat_code_block_style")
internal val ChatCodeBlockWrapEnabled = booleanPreferencesKey("chat_code_block_wrap_enabled")
internal val ChatCodeBlockShowAllEnabled = booleanPreferencesKey("chat_code_block_show_all_enabled")
internal val ChatAvatarShapeSocial = stringPreferencesKey("chat_avatar_shape_social")
internal val ChatAvatarShapeAgent = stringPreferencesKey("chat_avatar_shape_agent")
internal val ChatAvatarShapeRoleplay = stringPreferencesKey("chat_avatar_shape_roleplay")
internal val ChatRoleplayCardPanel = booleanPreferencesKey("chat_roleplay_card_panel")

// Every layout has its own explicit key for every shared metric.
internal val ChatBubbleCornerRadiusSocial = floatPreferencesKey("chat_bubble_corner_radius_social")
internal val ChatBubbleCornerRadiusAgent = floatPreferencesKey("chat_bubble_corner_radius_agent")
internal val ChatBubbleCornerRadiusRoleplay = floatPreferencesKey("chat_bubble_corner_radius_roleplay")
internal val ChatAvatarSizeSocial = floatPreferencesKey("chat_avatar_size_social")
internal val ChatAvatarSizeAgent = floatPreferencesKey("chat_avatar_size_agent")
internal val ChatAvatarSizeRoleplay = floatPreferencesKey("chat_avatar_size_roleplay")
internal val ChatNameFontSizeSocial = floatPreferencesKey("chat_name_font_size_social")
internal val ChatNameFontSizeAgent = floatPreferencesKey("chat_name_font_size_agent")
internal val ChatNameFontSizeRoleplay = floatPreferencesKey("chat_name_font_size_roleplay")
internal val ChatNameAvatarSpacingSocial = floatPreferencesKey("chat_name_avatar_spacing_social")
internal val ChatNameAvatarSpacingAgent = floatPreferencesKey("chat_name_avatar_spacing_agent")
internal val ChatNameAvatarSpacingRoleplay = floatPreferencesKey("chat_name_avatar_spacing_roleplay")
internal val ChatAreaHorizontalPaddingSocial = floatPreferencesKey("chat_area_horizontal_padding_social")
internal val ChatAreaHorizontalPaddingAgent = floatPreferencesKey("chat_area_horizontal_padding_agent")
internal val ChatAreaHorizontalPaddingRoleplay = floatPreferencesKey("chat_area_horizontal_padding_roleplay")
internal val ChatReplySpacingSocial = floatPreferencesKey("chat_reply_spacing_social")
internal val ChatReplySpacingAgent = floatPreferencesKey("chat_reply_spacing_agent")
internal val ChatReplySpacingRoleplay = floatPreferencesKey("chat_reply_spacing_roleplay")
internal val ChatTurnSpacingSocial = floatPreferencesKey("chat_turn_spacing_social")
internal val ChatTurnSpacingAgent = floatPreferencesKey("chat_turn_spacing_agent")
internal val ChatTurnSpacingRoleplay = floatPreferencesKey("chat_turn_spacing_roleplay")
internal val ChatMessageFontSizeSocial = floatPreferencesKey("chat_message_font_size_social")
internal val ChatMessageFontSizeAgent = floatPreferencesKey("chat_message_font_size_agent")
internal val ChatMessageFontSizeRoleplay = floatPreferencesKey("chat_message_font_size_roleplay")
internal val ChatLineHeightMultiplierSocial = floatPreferencesKey("chat_line_height_multiplier_social")
internal val ChatLineHeightMultiplierAgent = floatPreferencesKey("chat_line_height_multiplier_agent")
internal val ChatLineHeightMultiplierRoleplay = floatPreferencesKey("chat_line_height_multiplier_roleplay")
internal val ChatLetterSpacingSocial = floatPreferencesKey("chat_letter_spacing_social")
internal val ChatLetterSpacingAgent = floatPreferencesKey("chat_letter_spacing_agent")
internal val ChatLetterSpacingRoleplay = floatPreferencesKey("chat_letter_spacing_roleplay")
internal val ChatParagraphSpacingSocial = floatPreferencesKey("chat_paragraph_spacing_social")
internal val ChatParagraphSpacingAgent = floatPreferencesKey("chat_paragraph_spacing_agent")
internal val ChatParagraphSpacingRoleplay = floatPreferencesKey("chat_paragraph_spacing_roleplay")
internal val ChatWaitingAnimationSocial = stringPreferencesKey("chat_waiting_animation_social")
internal val ChatWaitingAnimationAgent = stringPreferencesKey("chat_waiting_animation_agent")
internal val ChatWaitingAnimationRoleplay = stringPreferencesKey("chat_waiting_animation_roleplay")
internal val ChatTimelineThinkingAnimationSocial =
    stringPreferencesKey("chat_timeline_thinking_animation_social")
internal val ChatTimelineThinkingAnimationAgent =
    stringPreferencesKey("chat_timeline_thinking_animation_agent")
internal val ChatTimelineThinkingAnimationRoleplay =
    stringPreferencesKey("chat_timeline_thinking_animation_roleplay")
internal val AppearanceThemeStored = booleanPreferencesKey("appearance_theme_stored")
internal val MobileBg = intPreferencesKey("appearance_mobile_bg")
internal val MobileRootBg = intPreferencesKey("appearance_mobile_root_bg")
internal val MobilePinnedBg = intPreferencesKey("appearance_mobile_pinned_bg")
internal val MobileSurface = intPreferencesKey("appearance_mobile_surface")
internal val MobileText = intPreferencesKey("appearance_mobile_text")
internal val MobileMuted = intPreferencesKey("appearance_mobile_muted")
internal val MobileSoft = intPreferencesKey("appearance_mobile_soft")
internal val MobileLine = intPreferencesKey("appearance_mobile_line")
internal val MobileSearchBg = intPreferencesKey("appearance_mobile_search_bg")
internal val MobileTopbarBg = intPreferencesKey("appearance_mobile_topbar_bg")
internal val MobileTabbarBg = intPreferencesKey("appearance_mobile_tabbar_bg")
internal val MobileChatBg = intPreferencesKey("appearance_mobile_chat_bg")
internal val MobileChatHeaderBg = intPreferencesKey("appearance_mobile_chat_header_bg")
internal val MobileChatMessageBg = intPreferencesKey("appearance_mobile_chat_message_bg")
internal val MobileChatMessageFg = intPreferencesKey("appearance_mobile_chat_message_fg")
internal val MobileChatUserBg = intPreferencesKey("appearance_mobile_chat_user_bg")
internal val MobileChatUserFg = intPreferencesKey("appearance_mobile_chat_user_fg")
internal val MobileChatTextureScrim = intPreferencesKey("appearance_mobile_chat_texture_scrim")
internal val MobileComposerBg = intPreferencesKey("appearance_mobile_composer_bg")
internal val MobileInputBg = intPreferencesKey("appearance_mobile_input_bg")
internal val MobileBlue = intPreferencesKey("appearance_mobile_blue")
internal val MobileAccentFg = intPreferencesKey("appearance_mobile_accent_fg")
internal val RootBackgroundImagePath = stringPreferencesKey("appearance_root_background_image_path")
internal val RootBackgroundOpacity = floatPreferencesKey("appearance_root_background_opacity")
internal val RootBackgroundBlur = floatPreferencesKey("appearance_root_background_blur")
internal val RootBackgroundScrim = floatPreferencesKey("appearance_root_background_scrim")
internal val TextureImagePath = stringPreferencesKey("appearance_texture_image_path")
internal val TextureOpacity = floatPreferencesKey("appearance_texture_opacity")
internal val TextureBlur = floatPreferencesKey("appearance_texture_blur")
internal val TextureScrim = floatPreferencesKey("appearance_texture_scrim")
internal val AppearanceIsDark = booleanPreferencesKey("appearance_is_dark")
internal val TextureScrimAngle = floatPreferencesKey("appearance_texture_scrim_angle")
internal val TextureScrimStart = floatPreferencesKey("appearance_texture_scrim_start")
internal val TextureScrimMid = floatPreferencesKey("appearance_texture_scrim_mid")
internal val TextureScrimEnd = floatPreferencesKey("appearance_texture_scrim_end")
internal val TextureScrimStartColor = intPreferencesKey("appearance_texture_scrim_start_color")
internal val TextureScrimEndColor = intPreferencesKey("appearance_texture_scrim_end_color")
internal val MarkdownItalicColor = intPreferencesKey("appearance_markdown_italic_color")
internal val MarkdownUnderlineColor = intPreferencesKey("appearance_markdown_underline_color")
internal val MarkdownQuoteColor = intPreferencesKey("appearance_markdown_quote_color")
internal val MarkdownInlineCodeColor = intPreferencesKey("appearance_markdown_inline_code_color")
internal val MarkdownCodeForegroundColor = intPreferencesKey("appearance_markdown_code_foreground_color")
internal val MarkdownCodeBackgroundColor = intPreferencesKey("appearance_markdown_code_background_color")
