package com.eleckoi.android.engine.agent.deepseek

import com.eleckoi.android.engine.agent.api.AgentSessionOptions
import com.eleckoi.android.engine.agent.tools.AgentToolRequestPolicy
import com.eleckoi.android.engine.workspace.runtime.RuntimePaths
import java.math.BigDecimal
import java.math.RoundingMode
import java.nio.file.Files
import java.nio.file.LinkOption
import java.nio.file.StandardCopyOption
import java.security.MessageDigest
import kotlinx.serialization.json.buildJsonArray
import kotlinx.serialization.json.buildJsonObject
import kotlinx.serialization.json.JsonPrimitive
import kotlinx.serialization.json.put

/** Materializes the Agent-plane composition consumed by DSH's official agent-presets plugin. */
internal class DshAgentPresetMaterializer private constructor(
    private val deepSeekHome: () -> java.io.File,
) {
    constructor(runtimePaths: RuntimePaths) : this({
        runtimePaths.workspaceDeepSeekHome(runtimePaths.persistentDeepSeekWorkspaceId)
    })

    internal constructor(deepSeekHome: java.io.File) : this({ deepSeekHome })

    fun materialize(
        options: AgentSessionOptions,
        systemInstructions: String,
        contextWindow: Int,
        autoCompactTokenLimit: Int?,
    ): String {
        val id = runtimePresetId(options, systemInstructions, contextWindow, autoCompactTokenLimit)
        val home = deepSeekHome()
        val root = secureDirectory(home, UserPresetDirectory)
        val directory = secureDirectory(root, id)
        writeIfChanged(
            directory.resolve(CompositionFile),
            composition(options, systemInstructions, contextWindow, autoCompactTokenLimit),
        )
        writeIfChanged(
            directory.resolve(MetadataFile),
            "name: ElecKoi Android\ndescription: ElecKoi 会话能力的 DSH Agent Preset\n",
        )
        return id
    }

    private fun runtimePresetId(
        options: AgentSessionOptions,
        systemInstructions: String,
        contextWindow: Int,
        autoCompactTokenLimit: Int?,
    ): String {
        val canonical = buildString {
            appendLine(CompositionVersion)
            appendLine(options.presetId.orEmpty())
            appendLine(options.enabledToolGroupIds.sorted().joinToString("\u001f"))
            appendLine(systemInstructions)
            appendLine(options.historyCompactionInstructions.orEmpty())
            appendLine(contextWindow)
            appendLine(autoCompactTokenLimit ?: "")
            options.dynamicTools
                .map { it.definition }
                .sortedBy { it.name }
                .forEach { definition ->
                    appendLine(definition.name)
                    appendLine(definition.description)
                    appendLine(definition.parameters.toString())
                }
        }
        val digest = MessageDigest.getInstance("SHA-256")
            .digest(canonical.toByteArray(Charsets.UTF_8))
            .take(16)
            .joinToString("") { "%02x".format(it.toInt() and 0xff) }
        return "eleckoi-$digest"
    }

    private fun composition(
        options: AgentSessionOptions,
        systemInstructions: String,
        contextWindow: Int,
        autoCompactTokenLimit: Int?,
    ): String = buildString {
        appendLine("# Generated by ElecKoi for @deepseek-ai/dsh-agent-presets.")
        appendLine("- id: eleckoi-persona")
        appendLine("  name: '@deepseek-ai/dsh-persona'")
        appendLine("  config:")
        appendLine("    prefix: ${JsonPrimitive(systemInstructions)}")
        appendLine("    suffix: ''")
        appendLine("    includeRuntimeContext: false")
        if (options.dynamicTools.isNotEmpty()) {
            appendLine()
            appendLine("- id: eleckoi-host-tools")
            appendLine("  name: /deepseek-home/eleckoi/eleckoi-host-tools.mjs")
            appendLine("  config:")
            appendLine("    baseUrl: !!js process.env.ELECKOI_HOST_TOOLS_URL")
            append("    tools: ")
            appendLine(dynamicToolsJson(options))
        }

        if (AgentToolRequestPolicy.BuiltInWorkspace in options.enabledToolGroupIds) {
            appendLine()
            appendLine("- id: tool-bash")
            appendLine("  name: '@deepseek-ai/dsh-tool-bash'")
            appendLine()
            appendLine("- id: fs-observation-policy")
            appendLine("  name: '@deepseek-ai/dsh-fs-observation-policy'")
            appendLine()
            appendLine("- id: tool-fs")
            appendLine("  name: '@deepseek-ai/dsh-tool-fs'")
            appendLine()
            appendLine("- id: tool-fs-search")
            appendLine("  name: '@deepseek-ai/dsh-tool-fs-search'")
            appendLine("  config:")
            appendLine("    sampleOverCapGlobResults: false")
        }
        if (AgentToolRequestPolicy.BuiltInWorkflow in options.enabledToolGroupIds) {
            appendLine()
            appendLine("- id: workflow")
            appendLine("  name: cordis:group")
            appendLine("  group: true")
            appendLine("  isolate:")
            appendLine("    workflowEngine: true")
            appendLine("  config:")
            appendLine("    - id: workflow-worker-thread")
            appendLine("      name: '@deepseek-ai/dsh-workflow-worker-thread'")
            appendLine("      config:")
            appendLine("        provider: spawn")
            appendLine()
            appendLine("    - id: tool-workflow")
            appendLine("      name: '@deepseek-ai/dsh-tool-workflow'")
            appendLine()
            appendLine("- id: tool-todo")
            appendLine("  name: '@deepseek-ai/dsh-tool-todo'")
            appendLine("  config:")
            appendLine("    allowParallelInProgress: true")
            appendLine()
            appendLine("- id: tool-jobs")
            appendLine("  name: '@deepseek-ai/dsh-tool-jobs'")
            appendLine()
            appendLine("- id: skill-filesystem")
            appendLine("  name: '@deepseek-ai/dsh-skill-filesystem'")
            appendLine()
            appendLine("- id: tool-skill")
            appendLine("  name: '@deepseek-ai/dsh-tool-skill'")
            appendLine()
            appendLine("- id: tool-goal")
            appendLine("  name: '@deepseek-ai/dsh-tool-goal'")
        }
        if (AgentToolRequestPolicy.BuiltInCollaboration in options.enabledToolGroupIds) {
            appendLine()
            appendLine("- id: tool-subagent-control")
            appendLine("  name: '@deepseek-ai/dsh-tool-subagent-control'")
            appendLine()
            appendLine("- id: tool-subagent-list")
            appendLine("  name: '@deepseek-ai/dsh-tool-subagent-control/list-agents'")
            appendLine()
            appendLine("- id: tool-subagent")
            appendLine("  name: '@deepseek-ai/dsh-tool-subagent'")
            appendLine("  config:")
            appendLine("    provider: spawn")
            appendLine("    toolName: subagent")
            appendLine("    backgroundMode: continuable")
            appendLine("    maxDepth: 2")
            appendLine()
            appendLine("- id: tool-subagent-fork")
            appendLine("  name: '@deepseek-ai/dsh-tool-subagent'")
            appendLine("  config:")
            appendLine("    provider: fork")
            appendLine("    toolName: subagent_fork")
            appendLine("    backgroundMode: one-shot")
            appendLine("    enableRunInBackground: false")
            appendLine("    maxDepth: 2")
        }

        val threshold = autoCompactTokenLimit
            ?.let { BigDecimal(it).divide(BigDecimal(contextWindow), 12, RoundingMode.HALF_UP) }
            ?.stripTrailingZeros()
            ?.toPlainString()
            ?: "0.8"
        appendLine()
        appendLine("- id: compaction")
        appendLine("  name: cordis:group")
        appendLine("  group: true")
        appendLine("  isolate:")
        appendLine("    compaction: true")
        appendLine("    toolResultPruner: true")
        appendLine("  config:")
        appendLine("    - id: compaction-basic")
        appendLine("      name: '@deepseek-ai/dsh-compaction-basic'")
        appendLine("      config:")
        appendLine("        thresholdRatio: $threshold")
        appendLine("        retainTokens: 0")
        appendLine("        maxTokens: 8192")
        appendLine("        compactionRetries: 1")
        options.historyCompactionInstructions
            ?.trim()
            ?.takeIf(String::isNotBlank)
            ?.let { instruction ->
                appendLine(
                    "        instruction: ${JsonPrimitive("$CompactionGuard\n\n$instruction")}",
                )
            }
        appendLine()
        appendLine("    - id: command-compact")
        appendLine("      name: '@deepseek-ai/dsh-command-compact'")
        appendLine()
        appendLine("    - id: tool-result-pruner")
        appendLine("      name: '@deepseek-ai/dsh-compaction-tool-result-pruner'")
        appendLine("      config:")
        appendLine("        thresholdChars: 8192")
        appendLine("        headChars: 4096")
        appendLine("        tailChars: 1024")
    }

    private fun dynamicToolsJson(options: AgentSessionOptions): String = buildJsonArray {
        options.dynamicTools
            .map { it.definition }
            .sortedBy { it.name }
            .forEach { definition ->
                add(buildJsonObject {
                    put("name", definition.name)
                    put("description", definition.description)
                    put("parameters", definition.parameters)
                })
            }
    }.toString()

    private fun secureDirectory(parent: java.io.File, name: String): java.io.File {
        require(name == UserPresetDirectory || PresetPathSegment.matches(name)) {
            "DSH Agent Preset 路径无效"
        }
        require(parent.isDirectory || parent.mkdirs()) { "无法创建 DSH Agent Preset 父目录" }
        require(!Files.isSymbolicLink(parent.toPath())) { "DSH Agent Preset 父目录不安全" }
        val directory = parent.resolve(name)
        require(directory.isDirectory || directory.mkdir()) { "无法创建 DSH Agent Preset 目录" }
        require(
            Files.isDirectory(directory.toPath(), LinkOption.NOFOLLOW_LINKS) &&
                !Files.isSymbolicLink(directory.toPath()) &&
                directory.canonicalFile.parentFile == parent.canonicalFile,
        ) { "DSH Agent Preset 目录不安全" }
        return directory.canonicalFile
    }

    private fun writeIfChanged(target: java.io.File, content: String) {
        val bytes = content.toByteArray(Charsets.UTF_8)
        if (Files.isRegularFile(target.toPath(), LinkOption.NOFOLLOW_LINKS) && target.readBytes().contentEquals(bytes)) return
        require(!Files.isSymbolicLink(target.toPath())) { "DSH Agent Preset 文件不安全" }
        val temporary = requireNotNull(target.parentFile).resolve(".${target.name}.tmp")
        require(!Files.isSymbolicLink(temporary.toPath())) { "DSH Agent Preset 临时文件不安全" }
        temporary.writeBytes(bytes)
        runCatching {
            Files.move(
                temporary.toPath(),
                target.toPath(),
                StandardCopyOption.ATOMIC_MOVE,
                StandardCopyOption.REPLACE_EXISTING,
            )
        }.getOrElse {
            Files.move(temporary.toPath(), target.toPath(), StandardCopyOption.REPLACE_EXISTING)
        }
    }

    private companion object {
        const val CompositionVersion = "dsh-0.1.5-rc.2-eleckoi-agent-preset-v3"
        const val CompactionGuard =
            "你当前只执行内部历史压缩。只返回非空的纯文本摘要正文；不要调用工具，" +
                "不要输出推理过程，也不要使用主对话的输出协议标签。"
        const val UserPresetDirectory = ".agent-presets"
        const val CompositionFile = "agent.cordis.yml"
        const val MetadataFile = "preset.yml"
        val PresetPathSegment = Regex("^[a-z0-9][a-z0-9-]*$")
    }
}
